# Generated by Django 5.2.13 on 2026-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(max_length=255)),
                ('subreddit', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(unique=True)),
                ('score', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('created_utc', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_news', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['subreddit', '-created_utc'], name='scraper_red_subredd_7a75e3_idx'), models.Index(fields=['-score'], name='scraper_red_score_09f589_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(db_index=True)),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['username', '-date'], name='scraper_twe_usernam_ea0485_idx')],
            },
        ),
    ]
