# Generated by Django 5.2.13 on 2026-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_news', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='scraper_thr_usernam_3a7f7a_idx')],
            },
        ),
    ]
