# Generated by Django 5.2.13 on 2026-05-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_threadspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do monitor')),
                ('subreddit', models.CharField(max_length=255, verbose_name='Subreddit')),
                ('keywords', models.TextField(blank=True, help_text='Palavras-chave separadas por vírgula', verbose_name='Palavras-chave')),
                ('min_score', models.IntegerField(default=10, verbose_name='Score mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('interval_minutes', models.IntegerField(default=15, verbose_name='Intervalo (minutos)')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última execução')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuração de Monitor',
                'verbose_name_plural': 'Configurações de Monitores',
            },
        ),
        migrations.CreateModel(
            name='FilteredPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_keywords', models.CharField(blank=True, max_length=500)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_sent', models.BooleanField(default=False, verbose_name='Notificado')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('reddit_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.redditpost')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.monitorconfig')),
            ],
            options={
                'verbose_name': 'Post Filtrado',
                'verbose_name_plural': 'Posts Filtrados',
                'unique_together': {('reddit_post', 'monitor')},
            },
        ),
    ]
