# Generated by Django 5.2.13 on 2026-05-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_monitorconfig_filteredpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('created_utc', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('matched_keywords', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AlterModelOptions(
            name='redditpost',
            options={'ordering': ['-created_utc']},
        ),
        migrations.RemoveField(
            model_name='monitorconfig',
            name='subreddit',
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='collect_comments',
            field=models.BooleanField(default=False, verbose_name='Coletar comentários'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='monitor_type',
            field=models.CharField(choices=[('subreddit', 'Subreddit'), ('user', 'Perfil de Usuário')], default='subreddit', max_length=20, verbose_name='Tipo de monitor'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Coletar posts desde esta data', null=True, verbose_name='Data inicial'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='target',
            field=models.CharField(default='brasil', help_text="Ex: 'brasil' para r/brasil ou 'username' para u/username", max_length=255, verbose_name='Alvo (subreddit ou usuário)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='interval_minutes',
            field=models.IntegerField(default=5, verbose_name='Intervalo (minutos)'),
        ),
        migrations.AddIndex(
            model_name='redditpost',
            index=models.Index(fields=['author', '-created_utc'], name='scraper_red_author_f31efc_idx'),
        ),
        migrations.AddField(
            model_name='redditcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scraper.redditpost'),
        ),
        migrations.AddIndex(
            model_name='redditcomment',
            index=models.Index(fields=['post', '-score'], name='scraper_red_post_id_98a8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='redditcomment',
            index=models.Index(fields=['author', '-created_utc'], name='scraper_red_author_5a352e_idx'),
        ),
    ]
