# Generated by Django 5.2.13 on 2026-05-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_redditcomment_alter_redditpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da fonte')),
                ('url', models.URLField(unique=True, verbose_name='URL do feed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_fetch', models.DateTimeField(blank=True, null=True, verbose_name='Última coleta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fonte RSS',
                'verbose_name_plural': 'Fontes RSS',
            },
        ),
        migrations.CreateModel(
            name='RSSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_news', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.rsssource')),
            ],
            options={
                'verbose_name': 'Entrada RSS',
                'verbose_name_plural': 'Entradas RSS',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['source', '-published_at'], name='scraper_rss_source__4f43b1_idx'), models.Index(fields=['-published_at'], name='scraper_rss_publish_29cc9c_idx')],
            },
        ),
    ]
